const express = require('express');
const path = require('path');

const winston = require('winston');
const pick = require('lodash.pick');
const Promise = require('bluebird');

const apputils = require('./utils');
const filtercache = require('./filtercache');
//const filterbuilder = require('./filterbuilder');

const fs = Promise.promisifyAll(require('fs'));

/**
 * Log level
 */
winston.level = process.env.LOG_LEVEL || 'error' ;

var router = express.Router();

/**
 * Utility function to allow wrapping every call in the express route with async
 * @param {function} fn 
 */
const asyncUtil = fn =>
        (req, res, next) =>
          fn(req, res, next)
            .catch(next);
 
            /*
router.get(
  '/searchFilter',
  asyncUtil( async (req, res, next) => {
    const filterObj = filterbuilder.searchFilter(req, res, next);
    const data = await filterbuilder.searchFilterQuery(filterObj);
    res.json(data)
  }
  )
);

*/


/**
 * Accepts a Keyword URL parameter and returns matches for it from the full filter cache
 * /keyword?kw=Acco 
 */
router.get(
  '/keyword',
  findKeyword
);

/**
 * Finds keywords using the full filter cache. 
 * NOTE: this makes use of the Promise form of the fs module.
 * where the APIs are generated by promisyfing fs using bluebird.
 * @param {object} req 
 * @param {object} res 
 * @param {object} next 
 */
function findKeyword(req, res, next) {
    const keyword = req.query.kw.toLowerCase() ;
    fs.openAsync(filtercache.getCacheFile(), 'r').then(
      function(fd) {
        fs.readFileAsync(filtercache.getCacheFile(), 'utf8')
          .then(
          function(contents) {
            let filterObj = JSON.parse(contents);
            let kwObjs = filterObj.filter.find(
              filter => filter.name === 'keywords'
            );
            let matches = kwObjs.keyword.filter(
               kwObj => kwObj.showAs.toLowerCase().indexOf(keyword) >= 0 
            );
            apputils.fsClose(fs, fd);
            res.json({matches: matches});
          }
        ).catch(
          function (error) {
              winston.log(" error in findKeyword " + error.message);
          }
        );
    }
  );
}



module.exports = router;
